import {StyleSheet, Dimensions} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FEFEFF',
  },
  headerView: {
    width: wp(110),
    height: hp(17),

    right: 14,
    // backgroundColor: 'green',
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginHorizontal: 12,
    // marginTop: 10,
  },
  backArrow_btn: {
    // backgroundColor: 'yellow',
    width: wp(20),
    height: hp(13),
  },
  backArrow_img: {
    // backgroundColor: 'red',
    alignSelf: 'center',
    marginTop: 40,
  },
  arrow_icon: {
    // backgroundColor: 'green',
    marginTop: 30,
    width: wp(8),
    height: hp(4),
    marginLeft: 25,
    // justifyContent: 'center',
    // alignSelf: 'center',
    // backgroundColor: 'purple',
  },

  header_txt: {
    alignSelf: 'center',
    marginTop: 20,

    // backgroundColor: 'green',
    color: 'black',
    fontFamily: 'Inter',
    fontSize: 22,
    fontWeight: 'bold',
  },
  header_desc: {
    width: wp(100),
    height: hp(13),
  },
  heading: {
    width: wp(90),
    // backgroundColor: 'green',
    alignSelf: 'center',
    // height: hp(13),
  },
  heading1: {
    marginTop: 15,
    width: wp(90),
    // backgroundColor: 'green',
    alignSelf: 'center',
    // height: hp(13),
  },
  header_txt: {
    alignSelf: 'center',
    // marginHorizontal: 34,
    marginTop: 35,
    marginRight: 85,
    // backgroundColor: 'green',
    color: '#fff',
    fontFamily: 'Inter',
    fontSize: 19,
    fontWeight: 'bold',
  },
  bodyContainer: {
    // width: wp(90),
    // height: hp(10.2),
    width: wp(70),
    // height: windowHeight / 10,
    backgroundColor: '#FFFFFF',
    alignSelf: 'center',
    // flexDirection: 'row',
    marginTop: 18,
    borderRadius: 6,
    borderWidth: 1,
    marginHorizontal: 10,
  },
  weather_detail: {
    fontSize: 15,
    marginTop: 10,
  },
  weather_detail1: {
    fontSize: 15,
    marginTop: 10,
    marginBottom: 10,
  },
  about_heading_txt: {
    alignSelf: 'center',
    marginTop: 35,

    // backgroundColor: 'green',
    color: '#DB1F55',
    fontFamily: 'Inter',
    fontSize: 22,
    // fontWeight: 'bold',
  },
  formField_container: {
    marginTop: 5,
    // backgroundColor: 'purple',
  },
  formInput_container: {
    width: wp(90),
    // height: hp(1),
    fontFamily: 'Inter',
    fontWeight: 'normal',
    fontSize: 16,
    color: '#000',
    alignSelf: 'center',
    // marginHorizontal: 15,
    // flex: 1,
    // marginTop: 5,
    // backgroundColor: 'red',
  },
  weather_container: {
    // backgroundColor: 'red',
    width: wp(90),
    height: hp(22),
    alignSelf: 'center',
    marginTop: 10,
    borderWidth: 1,
  },
  weather_flow: {
    backgroundColor: 'green',
    marginTop: 10,
    width: wp(60),
    height: hp(25),
    right: 30,
    alignSelf: 'center',
  },
  LineChart_Container: {
    // backgroundColor: 'yellow',
    marginTop: 10,
    width: wp(90),
    height: hp(30),
    alignSelf: 'center',
  },
  Button_Conatinerr: {
    width: wp(100),
    height: hp(7),
    marginTop: 10,
    marginBottom: 22,
    // backgroundColor: 'red',
    // justifyContent:'center',
    // alignSelf: 'center',
  },
  linearGradient: {
    width: wp(60),
    height: hp(7),
    // marginHorizontal: hp(3.5),
    alignSelf: 'center',
    backgroundColor: '#293C74',
    // padding: 17,

    borderRadius: 52,
  },
  buttonText: {
    fontSize: 14,
    color: '#fff',
    marginTop: hp(2.1),
    // backgroundColor: 'green',
    fontWeight: 'bold',
    textAlign: 'center',
    fontFamily: 'Inter',
  },
});
export default styles;
